

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    default_type  application/octet-stream;

    sendfile        on;
    sendfile_max_chunk 1024k;

    tcp_nopush     on;
    tcp_nodelay    on;
    keepalive_timeout  65;

    server {
    listen       3003;

    location / {
        root   /tmp/vol1;
        index  index.html index.htm;

        dav_methods PUT DELETE;
        dav_access group:rw all:r;
        create_full_put_path on;


        client_max_body_size 0;

        autoindex on;
    }
}
}
